### ISSUE TITLE
Gradio Blocks Demo

### ISSUE THREAD

**Issue by AK391** [FanChiMao/SRMNet-thesis#2]
Hi, great work on the Gradio demo https://huggingface.co/spaces/52Hz/SRMNet_thesis, would you be interested in making a gradio blocks version of this for the blocks event this month: https://huggingface.co/Gradio-Blocks or for another model, thanks!

**Comment by FanChiMao** [comment]
Thank you very much for the invitation, I will look into that for sure. 👌
